import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();

  factory LocalizationService() {
    return _instance;
  }

  LocalizationService._internal();

  Locale _currentLocale = const Locale('es');

  Locale get currentLocale => _currentLocale;

  void changeLocale(String languageCode) {
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  // Diccionario de traducciones simple
  final Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'app_title': 'StructureScan',
      'profile_title': 'Mi Perfil',
      'settings_title': 'Ajustes de la Aplicación',
      'notifications': 'Notificaciones',
      'security': 'Seguridad y Privacidad',
      'language': 'Idioma',
      'logout': 'Cerrar Sesión',
      'cancel': 'Cancelar',
      'confirm_logout': '¿Estás seguro de que quieres cerrar sesión?',
      'personal_info': 'Información Personal',
      'role': 'Rol',
      'phone': 'Teléfono',
      'location': 'Ubicación',
      'organization': 'Organización',
      'professional_profile': 'Perfil Profesional',
      'edit_professional_profile': 'Editar Perfil Profesional',
      'update_professional_info': 'Actualiza tu información profesional',
      'actions': 'Acciones',
      'select_language': 'Seleccionar Idioma',
      'language_changed': 'Idioma cambiado a',
      'notifications_push': 'Notificaciones Push',
      'notifications_email': 'Notificaciones por Correo',
      'notifications_new_requests': 'Nuevas Solicitudes',
      'notifications_status_updates': 'Actualizaciones de Estado',
      'notifications_marketing': 'Novedades y Ofertas',
      'save_changes': 'Guardar Cambios',
      'change_password': 'Cambiar Contraseña',
      'two_factor': 'Autenticación en dos pasos',
      'biometric': 'Face ID / Touch ID',
      'delete_account': 'Eliminar Cuenta',
      'danger_zone': 'Zona de Peligro',
      'owner': 'Propietario',
      'professional': 'Profesional',
      'user': 'Usuario',
      'general_preferences': 'Preferencias Generales',
      'activity': 'Actividad',
      'others': 'Otros',
      'notifications_push_subtitle': 'Recibir alertas en tu dispositivo',
      'notifications_email_subtitle': 'Recibir resúmenes y alertas importantes',
      'notifications_new_requests_subtitle': 'Cuando recibas una nueva solicitud de inspección',
      'notifications_status_updates_subtitle': 'Cambios en el estado de tus inspecciones',
      'notifications_marketing_subtitle': 'Información sobre nuevas funciones y promociones',
      'preferences_saved': 'Preferencias guardadas correctamente',
      'change_password_subtitle': 'Actualiza tu clave de acceso',
      'two_factor_subtitle': 'Añade una capa extra de seguridad',
      'biometric_subtitle': 'Usar biometría para iniciar sesión',
      'delete_account_subtitle': 'Esta acción es irreversible',
      'delete_account_confirm': '¿Estás seguro de que quieres eliminar tu cuenta permanentemente? Esta acción no se puede deshacer.',
      'delete_account_action': 'Eliminar Permanentemente',
      'delete_request_sent': 'Solicitud de eliminación enviada. Te contactaremos.',
      'password_mismatch': 'Las contraseñas no coinciden o están vacías',
      'password_updated': 'Contraseña actualizada correctamente',
      'error_updating': 'Error al actualizar',
      'new_password': 'Nueva Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'update': 'Actualizar',
      'account_security': 'Seguridad de la Cuenta',
      'biometric_access': 'Acceso Biométrico',
    },
    'en': {
      'app_title': 'StructureScan',
      'profile_title': 'My Profile',
      'settings_title': 'App Settings',
      'notifications': 'Notifications',
      'security': 'Security & Privacy',
      'language': 'Language',
      'logout': 'Log Out',
      'cancel': 'Cancel',
      'confirm_logout': 'Are you sure you want to log out?',
      'personal_info': 'Personal Information',
      'role': 'Role',
      'phone': 'Phone',
      'location': 'Location',
      'organization': 'Organization',
      'professional_profile': 'Professional Profile',
      'edit_professional_profile': 'Edit Professional Profile',
      'update_professional_info': 'Update your professional information',
      'actions': 'Actions',
      'select_language': 'Select Language',
      'language_changed': 'Language changed to',
      'notifications_push': 'Push Notifications',
      'notifications_email': 'Email Notifications',
      'notifications_new_requests': 'New Requests',
      'notifications_status_updates': 'Status Updates',
      'notifications_marketing': 'News & Offers',
      'save_changes': 'Save Changes',
      'change_password': 'Change Password',
      'two_factor': 'Two-Factor Authentication',
      'biometric': 'Face ID / Touch ID',
      'delete_account': 'Delete Account',
      'danger_zone': 'Danger Zone',
      'owner': 'Owner',
      'professional': 'Professional',
      'user': 'User',
      'general_preferences': 'General Preferences',
      'activity': 'Activity',
      'others': 'Others',
      'notifications_push_subtitle': 'Receive alerts on your device',
      'notifications_email_subtitle': 'Receive summaries and important alerts',
      'notifications_new_requests_subtitle': 'When you receive a new inspection request',
      'notifications_status_updates_subtitle': 'Changes in the status of your inspections',
      'notifications_marketing_subtitle': 'Information about new features and promotions',
      'preferences_saved': 'Preferences saved successfully',
      'change_password_subtitle': 'Update your access key',
      'two_factor_subtitle': 'Add an extra layer of security',
      'biometric_subtitle': 'Use biometrics to log in',
      'delete_account_subtitle': 'This action is irreversible',
      'delete_account_confirm': 'Are you sure you want to permanently delete your account? This action cannot be undone.',
      'delete_account_action': 'Permanently Delete',
      'delete_request_sent': 'Deletion request sent. We will contact you.',
      'password_mismatch': 'Passwords do not match or are empty',
      'password_updated': 'Password updated successfully',
      'error_updating': 'Error updating',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'update': 'Update',
      'account_security': 'Account Security',
      'biometric_access': 'Biometric Access',
    },
    'pt': {
      'app_title': 'StructureScan',
      'profile_title': 'Meu Perfil',
      'settings_title': 'Configurações do App',
      'notifications': 'Notificações',
      'security': 'Segurança e Privacidade',
      'language': 'Idioma',
      'logout': 'Sair',
      'cancel': 'Cancelar',
      'confirm_logout': 'Tem certeza que deseja sair?',
      'personal_info': 'Informações Pessoais',
      'role': 'Função',
      'phone': 'Telefone',
      'location': 'Localização',
      'organization': 'Organização',
      'professional_profile': 'Perfil Profissional',
      'edit_professional_profile': 'Editar Perfil Profissional',
      'update_professional_info': 'Atualize suas informações profissionais',
      'actions': 'Ações',
      'select_language': 'Selecionar Idioma',
      'language_changed': 'Idioma alterado para',
      'notifications_push': 'Notificações Push',
      'notifications_email': 'Notificações por E-mail',
      'notifications_new_requests': 'Novas Solicitações',
      'notifications_status_updates': 'Atualizações de Status',
      'notifications_marketing': 'Novidades e Ofertas',
      'save_changes': 'Salvar Alterações',
      'change_password': 'Alterar Senha',
      'two_factor': 'Autenticação em Dois Fatores',
      'biometric': 'Face ID / Touch ID',
      'delete_account': 'Excluir Conta',
      'danger_zone': 'Zona de Perigo',
      'owner': 'Proprietário',
      'professional': 'Profissional',
      'user': 'Usuário',
      'general_preferences': 'Preferências Gerais',
      'activity': 'Atividade',
      'others': 'Outros',
      'notifications_push_subtitle': 'Receber alertas no seu dispositivo',
      'notifications_email_subtitle': 'Receber resumos e alertas importantes',
      'notifications_new_requests_subtitle': 'Quando você receber uma nova solicitação de inspeção',
      'notifications_status_updates_subtitle': 'Mudanças no status de suas inspeções',
      'notifications_marketing_subtitle': 'Informações sobre novos recursos e promoções',
      'preferences_saved': 'Preferências salvas com sucesso',
      'change_password_subtitle': 'Atualize sua senha de acesso',
      'two_factor_subtitle': 'Adicione uma camada extra de segurança',
      'biometric_subtitle': 'Usar biometria para entrar',
      'delete_account_subtitle': 'Esta ação é irreversível',
      'delete_account_confirm': 'Tem certeza de que deseja excluir sua conta permanentemente? Esta ação não pode ser desfeita.',
      'delete_account_action': 'Excluir Permanentemente',
      'delete_request_sent': 'Solicitação de exclusão enviada. Entraremos em contato.',
      'password_mismatch': 'As senhas não coincidem ou estão vazias',
      'password_updated': 'Senha atualizada com sucesso',
      'error_updating': 'Erro ao atualizar',
      'new_password': 'Nova Senha',
      'confirm_password': 'Confirmar Senha',
      'update': 'Atualizar',
      'account_security': 'Segurança da Conta',
      'biometric_access': 'Acesso Biométrico',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }
}
